/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupins1

import kotlin.test.Test
import kotlin.test.assertEquals

class BalancedGroupingTest {
    val classUnderTest = BalancedGroupingProblem()

    @Test fun EmptyStringTest() {
        assertEquals(true, classUnderTest.isBalanced(" "))
    }
}
