/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupins1

class BalancedGroupingProblem {
    fun isBalanced(sequence: String): Boolean {
        return true
    }
}
