/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package BalancedGroupins1

import java.util.ArrayDeque

class BalancedGroupingProblem {
    fun isBalanced(sequence: String): Boolean {
        val stack = ArrayDeque<Char>()

        for (c in sequence) {
            if (c == '(' || c == '[' || c == '{') {
                stack.push(c)
            }
            else if (c == ')' || c == ']' || c == '}') {
                if (stack.size == 0)
                    return false
                else {
                    if (!isMatchingBracket(stack.pop(), c))
                        return false
                }
            }
        }

        if (stack.size > 0)
            return false
        else 
            return true
    }

    private fun isMatchingBracket(a: Char, b: Char): Boolean {
        if (a == '(' && b == ')')
            return true
        else if (a == '[' && b == ']')
            return true
        else if (a == '{' && b == '}')
            return true
        else
            return false
    }
}
